[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "Advanced-Geomtry-Math"
version = "0.0.1"
description = "A simple Python library for More Methods For Math ."
aurthor = ["Youssef Ahmed <youssefahmedmoawedhamied@gmail.com>]
